services:
  
  memcached:
    image: memcached
    cpuset: "1"
    command:
      - --conn-limit=1024
      - --memory-limit=64
      - --threads=4
    ports:
      - "11211:11211"
    
  
  
  orchestrator:
    build: orchestrator
    cpuset: "1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - memcached    
